# Name and metadata of your task
task_name: 'Koii VIP Marketing AI'
author: 'Koii'
description: "Turn your node into a VIP KOL. Key Opinion Leaders are a crucial part of growing the Koii community, but we often don't have enough time to be on Twitter all day.
Using Artificial Intelligence directly on your device, this task volunteers your spare Twitter account to help spread the word about Koii. 

The task will 
+ Like Koii Related Posts
+ Generate and leave AI Comments on related posts+ Retweet occasional Koii announcements
+ Help share your referral code

While running this task, you will receive rewards based on the number of views your AI agent gets on it's posts. 
Rewards are distributed in $VIP tokens, which entitle you to special offers and airdrops within the Koii community (including $KOII distributions weekly!)

Each round, 100 $VIP are released, and divided among all staked nodes based on how many views they received as a portion of the total views that round.
Lock in and start making passive income as your AI agent does the hard work!"
repositoryUrl: 'https://github.com/koii-network/task-X'
imageUrl: 'https://bafybeide6ywkth337mb37zye7l6b3xbxzu3ltqxqjrjotceofxiqzbbrpm.ipfs.w3s.link/image.png'
infoUrl: 'https://x.com/al_from_koii/status/1848790702186238018'

# network value can be DEVELOPMENT , ARWEAVE or IPFS, Recommended IPFS when deploying to testnet as the cli automatically takes care of uploading the executable with the help of web3.js key
task_executable_network: 'IPFS'

# Path to your executable webpack if the selected network is IPFS and in case of DEVELOPMENT  name it as main
task_audit_program: 'dist/main.js'

# Total round time of your task : it must be given in slots and each slot is roughly equal to 408ms
round_time: 6000
audit_window: 2500
submission_window: 2500

# Amounts in KOII
minimum_stake_amount: 0.1

# total_bounty_amount cannot be grater than bounty_amount_per_round
# total bounty is not accepted in case of update task
total_bounty_amount: 1000
bounty_amount_per_round: 10

#Number of times allowed to re-submit the distribution  list in case the distribution list is audited
allowed_failed_distributions: 3

#Space in MBs for the account size, that holds the task data
space: 0.1

# Note that the value field in RequirementTag is optional, so it is up to you to include it or not based on your use case.
# To add more global variables and task variables, please refer the type,value,description format shown below

requirementsTags:
  - type: TASK_VARIABLE
    value: 'TWITTER_USERNAME'
    description: 'The username of your volunteer Twitter account. Please ensure your volunteer Twitter account has passed the Twitter verification process.'
  - type: TASK_VARIABLE
    value: 'TWITTER_PASSWORD'
    description: 'The password of your volunteer Twitter account.'
  - type: TASK_VARIABLE
    value: 'TWITTER_VERIFICATION'
    description: 'If verification is required, will use your email or phone number to login.'
  - type: CPU
    value: '4-core'
  - type: RAM
    value: '5 GB'
  - type: STORAGE
    value: '5 GB'

## Task Bounty Type ##
# KOII or KPL
task_type: "KPL"

## Token Mint Address (ONLY for KPL tasks) ##
# The Fire Token address is provided as an example.
token_type: "3kh898gitJDSb6b7MsntLqyUAvy3Y6D4PkMyGfinubht"

tags: ['Social Posting']
environment: 'PRODUCTION'

# OPTIONAL Only provide the taskId if you are updating the task otherwise leave blank
task_id: '7WPRJc9845FrvZAnwQKnNhRPu3DfGw7WVWXS8LscAXjz'

# Provide the description for changes made in new version of task
migrationDescription: ''
